### ISSUE TITLE
No longer working with protractor 3.2.0

### ISSUE THREAD

**Issue by saltenasl** [teerapap/grunt-protractor-runner#151]
Throws:

Warning: Cannot find module 'protractor'

**Comment by mtheoryx** [comment]
+1

**Comment by mtheoryx** [comment]
This commit from Protractor fixes the issue. But they haven't tagged or version bumped, so npm isnt pulling it in:

https://github.com/angular/protractor/commit/6e029341a67cd985bf727285dec2ef10aafe7b6a

**Comment by mtheoryx** [comment]
Protractor just fixed and released 3.2.1. In the meantime of this lib getting that dep updated, if you explicitly add that version in your own dependencies, things should work.
